version: '3.0'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nestjs_rest_api
    networks:
      - freeBootstrap

    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  freeBootstrap:




    #  version: '3.8'
    # services:
    #   db:
    #     image: postgres:14.1-alpine
    #     restart: always
    #     environment:
    #       - POSTGRES_USER=postgres
    #       - POSTGRES_PASSWORD=postgres
    #     ports:
    #       - '5432:5432'
    #     volumes: 
    #       - db:/var/lib/postgresql/data
    # volumes:
    #   db:
    #     driver: local
